name: 'Docker check'

on:
  pull_request:
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-pr.yml'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0
      - name: Build Docker image
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
